### ISSUE TITLE
when I try to run this demo， I met a mistake. I could not  figure out why?

### ISSUE THREAD

**Issue by LittleBoyHack** [kimhc6028/soft-decision-tree#2]
Traceback (most recent call last):
  File "C:/Users/woai_fish/Desktop/android/soft-decision-tree-master/main.py", line 100, in <module>
    model.train_(train_loader, epoch)
  File "C:\Users\woai_fish\Desktop\android\soft-decision-tree-master\model.py", line 193, in train_
    loss, output = self.cal_loss(data, self.target_onehot)
  File "C:\Users\woai_fish\Desktop\android\soft-decision-tree-master\model.py", line 133, in cal_loss
    leaf_accumulator = self.root.cal_prob(x, self.path_prob_init)
  File "C:\Users\woai_fish\Desktop\android\soft-decision-tree-master\model.py", line 58, in cal_prob
    self.prob = self.forward(x)  # probability of selecting right node
  File "C:\Users\woai_fish\Desktop\android\soft-decision-tree-master\model.py", line 48, in forward
    return (F.sigmoid(self.beta * self.fc(x)))
  File "E:\Conda\envs\android\lib\site-packages\torch\autograd\variable.py", line 757, in __mul__
    return self.mul(other)
  File "E:\Conda\envs\android\lib\site-packages\torch\autograd\variable.py", line 301, in mul
    return Mul.apply(self, other)
  File "E:\Conda\envs\android\lib\site-packages\torch\autograd\_functions\basic_ops.py", line 50, in forward
    return a.mul(b)
RuntimeError: inconsistent tensor size at d:\downloads\pytorch-master-1\torch\lib\th\generic/THTensorMath.c:847

**Comment by kimhc6028** [comment]
I cannot reproduce this error. Would you tell me exactly what you did? and your pytorch/python version

**Comment by LittleBoyHack** [comment]
Yes,I also suspected this issue！I  am trying to  try another  python version!Can you tell me your tools version that have no errors?
My Version Message:
python=3.6
torch=0.1.12

**Comment by kimhc6028** [comment]
python 3.5.2
pytorch 0.3.1

**Comment by LittleBoyHack** [comment]
Thanks you very much! I will try it latter!

**Comment by kiki28** [comment]
I can't find pytorch 0.3.1!

**Comment by kimhc6028** [comment]
@kiki28 This repo is updated to match pytorch 0.4.0. Please pull master branch again, and update your pytorch to 0.4.0. That should work.
