### ISSUE TITLE
I can't solve it

### ISSUE THREAD

**Issue by kiki28** [kimhc6028/soft-decision-tree#5]
(python352) C:\Users\ZQ>python
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.__version__)
0.3.1.post2
>>> quit()

(python352) C:\Users\ZQ>python D:\soft_decision_tree\main.py
directory ./data already exists
Traceback (most recent call last):
  File "D:\soft_decision_tree\main.py", line 53, in <module>
    transforms.Normalize((0.1307,), (0.3081,))
  File "D:\Anaconda\envs\python352\lib\site-packages\torchvision\datasets\mnist.py", line 54, in __init__
    os.path.join(self.root, self.processed_folder, self.training_file))
  File "D:\Anaconda\envs\python352\lib\site-packages\torch\serialization.py", line 267, in load
    return _load(f, map_location, pickle_module)
  File "D:\Anaconda\envs\python352\lib\site-packages\torch\serialization.py", line 420, in _load
    result = unpickler.load()
AttributeError: Can't get attribute '_rebuild_tensor_v2' on <module 'torch._utils' from 'D:\\Anaconda\\envs\\python352\\lib\\site-packages\\torch\\_utils.py'>

**Comment by kimhc6028** [comment]
it seems like version of pytorch is unmatched.
https://github.com/pytorch/pytorch/issues/5729
As I updated it to match up to pytorch 0.4.0, pull master branch again, and update pytorch to 0.4.0.

**Comment by kiki28** [comment]
I meet a new error.
save_result() missing 1 required positional argument: 'acc'

**Comment by kimhc6028** [comment]
@kiki28 Fixed the issue. Pull master again plz.

**Comment by kiki28** [comment]
No errors after running. And no result image.
